### ISSUE TITLE
What's the problem I change OSGRenderer inheritance osgViewer: : CompositeViewer to modify?

### ISSUE THREAD

**Issue by mirro187** [openscenegraph/osgQt#40] opened 2020-07-16 06:36 UTC
My environment is win10 osg3.6.4 OSGEARTH2.10.0  GTX1660Ti.

**Comment by unelsson** [comment] 2020-11-25 21:29
This is a duplicate of this, part of the solution can be found here: https://github.com/openscenegraph/osgQt/issues/37

**Closed** 2021-04-01 09:18 UTC
